[package]
name = "midimapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
midly = "0.5.3"
anyhow = "1.0.75"
regex = "1.10.2"
log = "0.4.20"
